version: '3'

tasks:
  default:
    deps:
      - task: build:all

  build:all:
    - dub build
    - dub build :msg_gen
    - dub build :rcl_bind
    - dub build :rosidl_parser
    - |
      . /opt/ros/$ROS_DISTRO/setup.sh
      dub build :test_helper
    - dub build :test_msgs

  test:all:
    - |
      . /opt/ros/$ROS_DISTRO/setup.sh
      dub build :test_helper
      . test_helper/ament/install/setup.sh
      dub test
    - dub test :msg_gen
    - dub test :test_helper
    - dub test :rosidl_parser

  clean:
    - dub clean
    - rm -rf test_helper/ament/install
    - find . -name '.dub' -type d | xargs rm -rf
    - find . -name '*.a' -or -name '*-unittest' | xargs rm -rf
    - find . -name 'dub.selections.json' | grep -v msg_gen | xargs rm -rf
